# -*- coding: utf-8 -*-
"""talha second notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AoRoMl_e996d5Ra3xHrs-edzr_SLdU4N
"""

print("hello world")

name='Qazi Talha Ayub'
print( name )

name=input("WHAT IS YOUR NAME ?")
birth_year=input("WHAT IS YOUR BIRTH YEAR ?")
age= 2022 - int(birth_year)
print(name + " is " + str(age) + " years old " )

'apple' + 'grapes'

'apple' + str(5)



course='Phython For Beginners'
print(course.title ())

course=' Python For Beginners'
print('python'in course)

x=2.9
 print(round(x))

x=2.9
print(abs(-2.9))

total_marks=input(' What are your total marks? ')
marks_obtained=input(" What are your marks obtained? ")
your_percentage= int(marks_obtained) / int(total_marks) * 100
print( " you have got " + '[ ' + str(your_percentage) + ' ]' + " % marks " )

rupees=input("money in rupees? ")
dollar=round(int(rupees) / 234,2)
print("you have " + '[' + str(dollar) + ']' + '$')

is_cold= True
if is_cold:
  print(" its a hot day ")
  print(" drink plenty of water ")
else:
  print("its cold day ")
  print("wear warm clothes")
print("enjoy your day ")

has_high_income= True
has_good_credit=False

if has_high_income or has_good_credit:
  print('eligible_for_loan')
else:
  print('sorry_not_eligible_for_loan')

print("Thank You")

name="fjnfm"

if len(name)<3:
  print("name must b atleast of 3 characters")

elif len(name)>50:
  print("name must be a maximum of 50 characters")

else:
  print("name looks good")  

print("Have a sweet day ")

weight=int(input('weight: '))
unit=input("(L)bs or (K)g: ")

if unit.upper()=="L":
  converted=weight * 0.45
  print(f"you are {converted} kilos")

else:  
  converted=weight/0.45
  print(f"you are {converted} lbs") 

print("Too Good ")
